MONGODB_CONFIG:
  name: "ignition_test"              # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://localhost:27017"   # 数据库链接地址
  username: "root"                   # 数据库链接用户名
  password: "123456"                 # 数据库链接密码
  database: "fast_gateway_test"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: true                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能
MYSQL_CONFIG:
  name: "lowercode"
  type: "mysql"
  host: "162.14.72.240"
  port: 3307
  username: "root"
  password: "root"
  database: "lowercode"
  entities: "mysql"
  logging: false
  synchronize: true
GITGUB_CONFIG:
  CLIENT_ID: 7a3278ef4c923da9509b
  CLIENT_SECRETS: 6ce3753b4a41db318ad282d6e9fe3260d6f102c9
FEISHU_CONFIG:
  FEISHU_APP_ID: ''
  FEISHU_APP_SECRET: ''

